name: Update GitHub Activities

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

concurrency:
  group: update-activities
  cancel-in-progress: true

jobs:
  generate-activities:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add profile-3d-contrib/*.svg
          if git commit -m "chore: Update 3d contribution graph"; then
            git push
          fi
