name: Update GitHub Activities

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  generate-activities:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v6
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name herokwon
          git config user.email contact@herokwon.dev
          git add -A .
          git commit -m "generated"
          git push
